"""Initial schema

Revision ID: 7fcce0f0c5b1
Revises: 
Create Date: 2026-05-16 19:58:34.779539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcce0f0c5b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('inventory_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_user_active', 'products', ['user_id', 'is_active'], unique=False)
    op.create_table('competitor_products',
    sa.Column('competitor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=True),
    sa.Column('competitor_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('competitor_id')
    )
    op.create_table('price_predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_price', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('predicted_revenue', sa.Float(), nullable=True),
    sa.Column('predicted_demand', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_product_recent', 'price_predictions', ['product_id', 'created_at'], unique=False)
    op.create_table('sales_data',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('price_at_sale', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index('idx_product_date', 'sales_data', ['product_id', 'sale_date'], unique=False)
    op.create_table('price_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_own_product', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_products.competitor_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('idx_competitor_time', 'price_history', ['competitor_id', 'scraped_at'], unique=False)
    op.create_index('idx_product_time', 'price_history', ['product_id', 'scraped_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_time', table_name='price_history')
    op.drop_index('idx_competitor_time', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_product_date', table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index('idx_product_recent', table_name='price_predictions')
    op.drop_table('price_predictions')
    op.drop_table('competitor_products')
    op.drop_index('idx_user_active', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
